### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by taotaoafk** [AndroidModLoader/SAShaderL#2]
Hello, sorry for inconvenience, but can you help me to make a tool that is like to 3dMigoto(like, to be more specific, the fork that can use skins on genshin impact) but on android(bcz it is made for directX, and structure is for windows too...)? Or help me to think how make or try to do this...

**Comment by RusJJ** [comment]
Don't really understand the purpose. Better ask such things in our Discord, that's an out-of-topic issue
